name: Smartflix github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
      - name: frontend setup node modules
        run: cd client && npm i
      - name: build frontend
        run: cd client && npm run build
        env:
          CI: ""
      - name: test yml
        run: echo "Test success"
